version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: prophet_erp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d prophet_erp"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/prophet_erp
      - SECRET_KEY=your-secret-key-here
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./models:/app/models
    restart: unless-stopped

volumes:
  postgres_data: